<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5723" started-at="2019-07-02T10:32:42Z" finished-at="2019-07-02T10:32:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5723" started-at="2019-07-02T10:32:42Z" finished-at="2019-07-02T10:32:48Z">
      <class name="com.apiTests.BasicAuthTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.apiTests.BasicAuthTests@5622fdf]" name="setUp" is-config="true" duration-ms="269" started-at="2019-07-02T10:32:42Z" finished-at="2019-07-02T10:32:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="beforeexec()[pri:0, instance:com.apiTests.BasicAuthTests@5622fdf]" name="beforeexec" is-config="true" duration-ms="1" started-at="2019-07-02T10:32:42Z" finished-at="2019-07-02T10:32:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeexec -->
        <test-method status="PASS" signature="basicAuthorization(java.lang.String, java.lang.String)[pri:0, instance:com.apiTests.BasicAuthTests@5622fdf]" name="basicAuthorization" duration-ms="3125" started-at="2019-07-02T10:32:42Z" data-provider="credentialDataSet" finished-at="2019-07-02T10:32:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[revell938@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Cybage@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicAuthorization -->
        <test-method status="FAIL" signature="basicAuthorization(java.lang.String, java.lang.String)[pri:0, instance:com.apiTests.BasicAuthTests@5622fdf]" name="basicAuthorization" duration-ms="992" started-at="2019-07-02T10:32:45Z" data-provider="credentialDataSet" finished-at="2019-07-02T10:32:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[revell938@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
same how bad request or credentials worng  expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
same how bad request or credentials worng  expected [200] but found [401]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.apiTests.BasicAuthTests.basicAuthorization(BasicAuthTests.java:159)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicAuthorization -->
        <test-method status="FAIL" signature="basicAuthorization(java.lang.String, java.lang.String)[pri:0, instance:com.apiTests.BasicAuthTests@5622fdf]" name="basicAuthorization" duration-ms="789" started-at="2019-07-02T10:32:46Z" data-provider="credentialDataSet" finished-at="2019-07-02T10:32:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[revell938@gmail]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Cybage@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
same how bad request or credentials worng  expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
same how bad request or credentials worng  expected [200] but found [401]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.apiTests.BasicAuthTests.basicAuthorization(BasicAuthTests.java:159)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicAuthorization -->
        <test-method status="FAIL" signature="basicAuthorization(java.lang.String, java.lang.String)[pri:0, instance:com.apiTests.BasicAuthTests@5622fdf]" name="basicAuthorization" duration-ms="782" started-at="2019-07-02T10:32:47Z" data-provider="credentialDataSet" finished-at="2019-07-02T10:32:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
same how bad request or credentials worng  expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
same how bad request or credentials worng  expected [200] but found [401]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.apiTests.BasicAuthTests.basicAuthorization(BasicAuthTests.java:159)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicAuthorization -->
        <test-method status="PASS" signature="closeSessions()[pri:0, instance:com.apiTests.BasicAuthTests@5622fdf]" name="closeSessions" is-config="true" duration-ms="3" started-at="2019-07-02T10:32:48Z" finished-at="2019-07-02T10:32:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeSessions -->
      </class> <!-- com.apiTests.BasicAuthTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
